FROM djangobox/django-docker-box:3.12
RUN wget https://www.sqlite.org/2024/sqlite-autoconf-3470200.tar.gz
RUN mkdir -p /tmp/sqlite && tar -xvzf sqlite-autoconf-3470200.tar.gz -C /tmp/sqlite
RUN cd /tmp/sqlite/sqlite-autoconf-3470200 && ./configure && make
ENV LD_LIBRARY_PATH="/tmp/sqlite/sqlite-autoconf-3470200/.libs"
WORKDIR /tests/django/tests
